title: Talend Demos
description: With attention to tJava* components and custom code. Examples include HTML & Json parsing.   
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
baseurl: '/talend_demos'